[tool.black]
line-length = 80
extend-exclude = ".*/migrations/.*py"

[tool.pytest.ini_options]
env = ["DJANGO_SETTINGS_MODULE=service.settings"]

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
check_untyped_defs = true

[tool.django-stubs]
django_settings_module = "service.settings"

[tool.pylint.format]
max-line-length = 80

[tool.pylint.MASTER]
ignore-paths = [".*/migrations/.*py"]
load-plugins = "pylint_django"

[tool.isort]
profile = "black"
line_length = 80
skip_glob = ["**/migrations/*.py"]
