[tool.black]
line-length = 80

[tool.pytest.ini_options]
env = ["DJANGO_SETTINGS_MODULE=service.settings"]

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "service.settings"

[tool.pylint.format]
max-line-length = 80
