"""
Django settings for service project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Custom

EMAIL_VERIFICATION_TIMEOUT = 60 * 60 * 24

DOTDIGITAL_CAMPAIGN_IDS = {
    "verify_email_address_1st_reminder": 0,  # TODO: set correct id
    "verify_email_address_2nd_reminder": 0,  # TODO: set correct id
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Custom
LOGIN_REDIRECT_URL = "/teach/dashboard/"
SILENCED_SYSTEM_CHECKS = ["captcha.recaptcha_test_key_error"]
RECAPTCHA_DOMAIN = "www.recaptcha.net"

PASSWORD_RESET_TIMEOUT = 3600

# This is used in common to enable/disable the OneTrust cookie management script
COOKIE_MANAGEMENT_ENABLED = False

SITE_ID = 1

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

MODULE_NAME = os.getenv("MODULE_NAME", "local")

"""RAPID ROUTER SETTINGS"""
# TODO: The settings in this section are needed for the old Rapid Router
#  package. Remove once RR has moved to the new system.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
                "sekizai.context_processors.sekizai",
                # TODO: replace in new system and remove here
                # "common.context_processors.module_name",
                # "common.context_processors.cookie_management_enabled",
                # TODO: use when integrating dotmailer
                # "portal.context_processors.process_newsletter_form",
            ]
        },
    }
]

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

PIPELINE_ENABLED = False  # True if assets should be compressed, False if not.
PIPELINE = {}

if os.environ.get("STATIC_MODE", "") == "pipeline":
    STATICFILES_FINDERS = ["pipeline.finders.PipelineFinder"]
    STATICFILES_STORAGE = "pipeline.storage.PipelineStorage"

    PIPELINE = {
        "COMPILERS": ("portal.pipeline_compilers.LibSassCompiler",),
        "STYLESHEETS": {
            "css": {
                "source_filenames": (
                    os.path.join(BASE_DIR, "static/portal/sass/bootstrap.scss"),
                    os.path.join(BASE_DIR, "static/portal/sass/colorbox.scss"),
                    os.path.join(BASE_DIR, "static/portal/sass/styles.scss"),
                    os.path.join(
                        BASE_DIR, "static/game/css/level_selection.css"
                    ),
                    os.path.join(BASE_DIR, "static/game/css/backgrounds.css"),
                ),
                "output_filename": "portal.css",
            },
            "game-scss": {
                "source_filenames": (
                    os.path.join(BASE_DIR, "static/game/sass/game.scss"),
                ),
                "output_filename": "game.css",
            },
            "popup": {
                "source_filenames": (
                    os.path.join(
                        BASE_DIR, "static/portal/sass/partials/_popup.scss"
                    ),
                ),
                "output_filename": "popup.css",
            },
        },
        "CSS_COMPRESSOR": None,
        "SASS_ARGUMENTS": "--quiet",
    }
else:
    STATICFILES_FINDERS = [
        "django.contrib.staticfiles.finders.AppDirectoriesFinder",
        "django.contrib.staticfiles.finders.FileSystemFinder",
    ]
# pylint: disable-next=pointless-string-statement
"""END OF RAPID ROUTER SETTINGS"""


# Domain
# TODO: Check if CSP still needs it after it's revisited
def domain():
    """
    Returns the full domain depending on whether it's local, dev, staging or
    prod.
    """
    domain_name = "https://www.codeforlife.education"

    if MODULE_NAME == "local":
        domain_name = "localhost:8000"
    elif MODULE_NAME == "staging":
        domain_name = "https://staging-dot-decent-digit-629.appspot.com"
    elif MODULE_NAME == "development":
        domain_name = (
            "https://development-portal-dot-decent-digit-629.appspot.com"
        )

    return domain_name


# CSP
# TODO: A lot of the links mentioned in the CSP will not be relevant with the
#  new system anymore. Update and clean the CSP settings once the frontend
#  has been done. Currently still needed for RR.
CSP_DEFAULT_SRC = ("self",)
CSP_CONNECT_SRC = (
    "'self'",
    "https://api.pwnedpasswords.com",
    "https://*.onetrust.com/",
    "https://euc-widget.freshworks.com/",
    "https://codeforlife.freshdesk.com/",
    "https://api.iconify.design/",
    "https://api.simplesvg.com/",
    "https://api.unisvg.com/",
    "https://www.google-analytics.com/",
    "https://region1.google-analytics.com/g/",
    "https://pyodide-cdn2.iodide.io/v0.15.0/full/",
    "https://crowdin.com/",
    "https://o2.mouseflow.com/",
    "https://stats.g.doubleclick.net/",
    f"wss://{MODULE_NAME}-aimmo.codeforlife.education/",
    f"https://{MODULE_NAME}-aimmo.codeforlife.education/",
)
CSP_FONT_SRC = (
    "'self'",
    "https://fonts.gstatic.com/",
    "https://fonts.googleapis.com/",
    "https://use.typekit.net/",
)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdn.crowdin.com/",
    "https://*.onetrust.com/",
    "https://code.jquery.com/",
    "https://euc-widget.freshworks.com/",
    "https://cdn-ukwest.onetrust.com/",
    "https://code.iconify.design/2/2.0.3/iconify.min.js",
    "https://www.googletagmanager.com/",
    "https://www.google-analytics.com/analytics.js",
    "https://cdn.mouseflow.com/",
    "https://www.recaptcha.net/",
    "https://www.google.com/recaptcha/",
    "https://www.gstatic.com/recaptcha/",
    "https://use.typekit.net/mrl4ieu.js",
    "https://pyodide-cdn2.iodide.io/v0.15.0/full/",
    f"{domain()}/static/portal/",
    f"{domain()}/static/common/",
    "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js",
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://euc-widget.freshworks.com/",
    "https://cdn-ukwest.onetrust.com/",
    "https://fonts.googleapis.com/",
    "https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css",
    "https://cdn.crowdin.com/",
    f"{domain()}/static/portal/",
)
CSP_FRAME_SRC = (
    "https://storage.googleapis.com/",
    "https://www.youtube-nocookie.com/",
    "https://www.recaptcha.net/",
    "https://www.google.com/recaptcha/",
    "https://crowdin.com/",
    f"{domain()}/static/common/img/",
    f"{domain()}/static/game/image/",
)
CSP_IMG_SRC = (
    "https://storage.googleapis.com/codeforlife-assets/images/",
    "https://cdn-ukwest.onetrust.com/",
    "https://p.typekit.net/",
    "https://cdn.crowdin.com/",
    "https://crowdin-static.downloads.crowdin.com/",
    "https://www.google-analytics.com/",
    "data:",
    f"{domain()}/static/portal/img/",
    f"{domain()}/static/portal/static/portal/img/",
    f"{domain()}/static/portal/img/",
    f"{domain()}/favicon.ico",
    f"{domain()}/img/",
    f"{domain()}/account/two_factor/qrcode/",
    f"{domain()}/static/",
    f"{domain()}/static/game/image/",
    f"{domain()}/static/game/raphael_image/",
    f"{domain()}/static/game/js/blockly/media/",
    f"{domain()}/static/icons/",
)
CSP_OBJECT_SRC = (
    f"{domain()}/static/common/img/",
    f"{domain()}/static/game/image/",
)
CSP_MEDIA_SRC = (
    f"{domain()}/static/react/",
    f"{domain()}/static/game/sound/",
    f"{domain()}/static/game/js/blockly/media/",
    f"{domain()}/static/portal/video/",
)
CSP_MANIFEST_SRC = (f"{domain()}/static/manifest.json",)

# pylint: disable-next=wrong-import-position,wildcard-import,unused-wildcard-import
from codeforlife.settings import *

DATABASES = get_databases(BASE_DIR)

# TODO: Go through the commented out middleware and decide if we still need them
MIDDLEWARE = [
    *MIDDLEWARE,
    # "deploy.middleware.admin_access.AdminAccessMiddleware",
    # "deploy.middleware.security.CustomSecurityMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # "deploy.middleware.session_timeout.SessionTimeoutMiddleware",
    # "deploy.middleware.exceptionlogging.ExceptionLoggingMiddleware",
    # "django_otp.middleware.OTPMiddleware",
    "csp.middleware.CSPMiddleware",
    # "deploy.middleware.screentime_warning.ScreentimeWarningMiddleware",
]

INSTALLED_APPS = [
    "api",
    "aimmo",
    "game",
    "pipeline",
    "portal",
    "captcha",
    "common",
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "import_export",
    "sekizai",  # for javascript and css management
    "treebeard",
    "sso",
    "rapid_router",
    *INSTALLED_APPS,
]
