name: Main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/backend.yaml@snyk
    secrets: inherit
    with:
      source-path: src
