name: Cypress
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🎓 Install dependencies
        run: npm install

      # report machine parameters
      # - run: yarn cypress info
      - run: npx cypress info
      - run: node -p 'os.cpus()'
      - run: npm run build
      # - run: yarn build

      - name: 📁 Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🎓 Install dependencies
        run: npm install

      - name: 🧹 Run linting
        run: npm run lint

      # - name: 🃏 Run Jest
      #   run: yarn test --ci --coverage

      # - name: ✅ Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3.1.0

  # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
  ui-chrome-tests-main:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # runs copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🏗 Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: 💻 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          start: yarn run develop:ci
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome - Main"
          spec: "cypress/e2e/main/*"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
