name: Main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/backend.yaml@convert_to_backend_repo # TODO: set to @main
    secrets: inherit
