name: Main

on: [push]

env:
  CYPRESS_WAIT_ON: http://localhost:8000
  CYPRESS_WAIT_ON_TIMEOUT: 300
  CYPRESS_SPEC: frontend/cypress/e2e/**/*.cy.ts

jobs:
  # The below code was adapted from this documentation.
  # https://docs.cypress.io/guides/continuous-integration/github-actions#Parallelization
  # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
  test-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: 🧪 Test on Chrome
        uses: cypress-io/github-action@v5.6.1
        with:
          working-directory: frontend
          #TODO: Currently using the run script for local development
          start: bash ../run
          wait-on: ${{ env.CYPRESS_WAIT_ON }}
          wait-on-timeout: ${{ env.CYPRESS_WAIT_ON_TIMEOUT }}
          browser: chrome
          record: true
          spec: ${{ env.CYPRESS_SPEC }}
          cache-key: os-${{ runner.os }}-dependencies-${{ hashFiles('frontend/yarn.lock') }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Report test info
        working-directory: frontend
        run: npx cypress info

      - name: 🔍 Report CPU info
        working-directory: frontend
        run: node -p 'os.cpus()'

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
