name: Cypress
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🎓 Install dependencies
        run: yarn install

      # report machine parameters
      - run: npx cypress info
      - run: node -p 'os.cpus()'
      - run: yarn build

      - name: 📁 Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🎓 Install dependencies
        run: yarn install

      - name: 🧹 Run linting
        run: yarn lint

  # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
  ui-chrome-tests-main:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    needs: install
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v3

      - name: 🏗 Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: 💻 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          start: yarn run ci:instrument
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome - Main"
          spec: "cypress/e2e/main/*"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
